import { execa } from "execa"
import type { ProjectAnalysis, GeneratedFile } from "../analyzer/types.js"
import type { AdapterStack } from "../adapters/index.js"
import type { BackupManager } from "./rollback.js"
import { runGenerators } from "../generators/index.js"
import { detectPackageManager, getRequiredDependencies, getMissingDependencies, installDependencies } from "./deps.js"
import { runMigrations } from "./migrations.js"
import { saveWizardConfig } from "../types/config.js"
import { logger } from "../utils/logger.js"
import { promises as fsPromises } from "fs"
import path from "path"

const TOTAL_OUTER_STEPS = 8

// ---------------------------------------------------------------------------
// runInstaller — phases 3-8 of the init command
// ---------------------------------------------------------------------------

export async function runInstaller(
  projectRoot: string,
  analysis: ProjectAnalysis,
  adapters: AdapterStack,
  backup: BackupManager,
  options: { dryRun?: boolean },
): Promise<void> {
  const dryRun = options.dryRun === true

  if (dryRun) {
    logger.warn("Dry-run mode enabled — no files will be written and no commands will run.")
  }

  // ── Step 3: Generate files ────────────────────────────────────────────────
  logger.step(3, TOTAL_OUTER_STEPS, "Generating files...")

  let generatedFiles: GeneratedFile[] = []
  let layoutModified = false
  let layoutPath = analysis.layout.filePath

  if (dryRun) {
    logger.section("Dry run — no files will be written")
    logger.info(`Would install in: ${projectRoot}`)
    logger.info(`Auth: ${analysis.auth.provider}`)
    logger.info(`ORM: ${analysis.orm.provider}`)
    logger.info(`Storage: ${analysis.storage.provider}`)
    logger.info(`Modules: ${analysis.modules.map((m) => m.name).join(", ")}`)
    logger.info("Files that would be generated:")
    const baseDir = analysis.hasSrcDir ? "src" : ""
    logger.info(`  ${baseDir}/types/improvements.ts`)
    logger.info(`  ${baseDir}/actions/improvements.ts`)
    logger.info(`  ${baseDir}/components/features/improvements/ (11 files)`)
    logger.info("  prisma/schema.prisma (appended)")
    logger.info(`Layout that would be modified: ${analysis.layout.filePath}`)
    return
  }

  const result = await runGenerators(analysis, adapters, backup)
  generatedFiles = result.files
  layoutModified = result.layoutModified
  layoutPath = analysis.layout.filePath

  // ── Step 4: Schema is generated as part of runGenerators (step 3) ─────────
  // runGenerators already calls generateSchema internally (step 3 of 5 within generators).
  // We log the outer step for UX clarity.
  logger.step(4, TOTAL_OUTER_STEPS, "Modifying DB schema...")
  logger.info("Schema files generated by the generator — see output above.")

  // ── Step 5: Layout injection ───────────────────────────────────────────────
  // Layout injection is also handled inside runGenerators (step 4 of 5).
  logger.step(5, TOTAL_OUTER_STEPS, "Injecting into layout...")
  if (layoutModified) {
    logger.success(`Layout injection complete: ${layoutPath}`)
  } else {
    logger.info("Layout injection skipped (already injected or file not found).")
  }

  // ── Step 6: Install dependencies ──────────────────────────────────────────
  logger.step(6, TOTAL_OUTER_STEPS, "Installing dependencies...")

  const required = await getRequiredDependencies(adapters)
  const missing = await getMissingDependencies(projectRoot, required)

  if (missing.length === 0) {
    logger.success("All required dependencies are already installed.")
  } else {
    logger.info(`Installing ${missing.length} missing package(s): ${missing.join(", ")}`)
    const pm = await detectPackageManager(projectRoot)
    await installDependencies(projectRoot, missing, pm)
  }

  // ── Step 7: TypeScript check ───────────────────────────────────────────────
  // Run BEFORE migrations so that a type error rolls back generated files
  // without leaving a half-applied DB migration behind.
  logger.step(7, TOTAL_OUTER_STEPS, "Verifying TypeScript...")

  try {
    await execa("npx", ["tsc", "--noEmit"], {
      cwd: projectRoot,
      stdio: "inherit",
    })
  } catch (err) {
    logger.error("TypeScript check failed — rolling back changes")
    await backup.rollbackAll()
    throw err
  }

  // ── Step 8: Run migrations ─────────────────────────────────────────────────
  // Only runs when TypeScript is clean. No file rollback is possible after this
  // point because `prisma migrate dev` cannot be undone automatically.
  logger.step(8, TOTAL_OUTER_STEPS, "Running migrations...")
  await runMigrations(projectRoot, analysis)

  // ── Commit + write config ───────────────────────────────────────────────────
  await backup.commit()

  // Separate files the wizard CREATED from files it only MODIFIED.
  // schema.prisma (Prisma / none provider) is appended to, not created from
  // scratch — it must not be deleted on uninstall.
  const schemaRelative =
    analysis.orm.provider === "prisma" && "schemaPath" in analysis.orm
      ? analysis.orm.schemaPath
      : "prisma/schema.prisma"

  const isPrismaLike =
    analysis.orm.provider === "prisma" || analysis.orm.provider === "none"

  const modifiedFilePaths: string[] = []
  const createdFilePaths: string[] = []

  for (const f of generatedFiles) {
    if (isPrismaLike && f.path === schemaRelative) {
      modifiedFilePaths.push(f.path)
    } else {
      createdFilePaths.push(f.path)
    }
  }

  await saveWizardConfig(projectRoot, {
    version: await readCliVersion(),
    installedAt: new Date().toISOString(),
    projectRoot,
    analysis: {
      auth: {
        provider: analysis.auth.provider,
        version: "version" in analysis.auth ? analysis.auth.version : undefined,
        variant: "variant" in analysis.auth ? analysis.auth.variant : undefined,
      },
      orm: {
        provider: analysis.orm.provider,
        client: "client" in analysis.orm ? analysis.orm.client : undefined,
      },
      storage: {
        provider: analysis.storage.provider,
        bucketName:
          "bucket" in analysis.storage && analysis.storage.bucket
            ? analysis.storage.bucket
            : "feedback-wizard",
      },
      ui: {
        provider: analysis.ui.provider,
      },
      modules: analysis.modules.map((m) => m.name),
      tablePrefix: analysis.projectName,
      dbTablePrefix: analysis.projectName.replace(/-/g, "_"),
    },
    generatedFiles: createdFilePaths,
    modifiedFiles: modifiedFilePaths,
    layoutModified,
    layoutPath,
  })
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function readCliVersion(): Promise<string> {
  try {
    // Walk up from this file to find package.json
    const pkgPath = path.resolve(
      path.dirname(new URL(import.meta.url).pathname),
      "../../package.json",
    )
    const raw = await fsPromises.readFile(pkgPath, "utf-8")
    const pkg = JSON.parse(raw) as { version?: string }
    return typeof pkg.version === "string" ? pkg.version : "0.0.0"
  } catch {
    return "0.0.0"
  }
}
