import type {
  DetectedAuth,
  DetectedORM,
  DetectedStorage,
  DetectedUI,
  DetectionResult,
  GeneratedFile,
  ProjectAnalysis,
  ProjectFiles,
} from "../analyzer/types.js"

// ---------------------------------------------------------------------------
// Plugin contract version
// ---------------------------------------------------------------------------

export const PLUGIN_CONTRACT_VERSION = "1.0" as const
export type PluginContractVersion = typeof PLUGIN_CONTRACT_VERSION

// ---------------------------------------------------------------------------
// Shared plugin metadata
// ---------------------------------------------------------------------------

export type PluginMeta = {
  /** Unique identifier, e.g. "auth:supabase" */
  id: string
  /** Human-readable display name */
  name: string
  /** Short description shown in logs */
  description: string
  /** Plugin contract version this adapter targets */
  contractVersion: PluginContractVersion
}

// ---------------------------------------------------------------------------
// Auth adapter plugin
// ---------------------------------------------------------------------------

export interface AuthAdapterPlugin {
  readonly meta: PluginMeta & { kind: "auth" }

  /**
   * Detect whether this auth provider is used in the project.
   * Must always return a result — never throw.
   */
  detect(files: ProjectFiles): Promise<DetectionResult<DetectedAuth>>

  /**
   * Generate the code snippet that retrieves the current user's ID
   * inside a Server Action or API route.
   */
  generateGetUserIdSnippet(analysis: ProjectAnalysis): string

  /**
   * Generate any files required to wrap or configure auth
   * (e.g. a `withAuth` HOC, middleware snippet, etc.).
   */
  generateFiles(analysis: ProjectAnalysis): Promise<GeneratedFile[]>

  /**
   * Returns the list of environment variable keys that need to be set.
   */
  requiredEnvVars(analysis: ProjectAnalysis): string[]
}

// ---------------------------------------------------------------------------
// ORM adapter plugin
// ---------------------------------------------------------------------------

export interface ORMAdapterPlugin {
  readonly meta: PluginMeta & { kind: "orm" }

  detect(files: ProjectFiles): Promise<DetectionResult<DetectedORM>>

  /**
   * Generate the Prisma/Drizzle schema additions or raw SQL migration
   * needed to store feedback data.
   */
  generateMigration(analysis: ProjectAnalysis): Promise<GeneratedFile[]>

  /**
   * Generate the repository/query helpers used by the wizard's Server Actions.
   */
  generateQueryHelpers(analysis: ProjectAnalysis): Promise<GeneratedFile[]>

  /**
   * Shell commands to run after files are written
   * (e.g. `prisma migrate dev --name feedback-wizard`).
   */
  postInstallCommands(analysis: ProjectAnalysis): string[]

  /**
   * Returns the import block for the ORM client.
   * e.g. `import { prisma } from "@/lib/prisma"`
   */
  getImportsBlock(analysis: ProjectAnalysis): string

  /**
   * Returns the client initialization block.
   * May be an empty string if the client is already initialized in the import.
   */
  getClientInitBlock(analysis: ProjectAnalysis): string

  /**
   * Returns the import statement for the enums generated by the ORM.
   * e.g. `import { ImprovementStatus } from "@prisma/client"`
   */
  getEnumImportBlock(tablePrefix: string): string
}

// ---------------------------------------------------------------------------
// Storage adapter plugin
// ---------------------------------------------------------------------------

export interface StorageAdapterPlugin {
  readonly meta: PluginMeta & { kind: "storage" }

  detect(files: ProjectFiles): Promise<DetectionResult<DetectedStorage>>

  /**
   * Generate the upload helper used to store feedback attachments.
   */
  generateUploadHelper(analysis: ProjectAnalysis): Promise<GeneratedFile[]>

  /**
   * Generate a signed-URL or public-URL resolver for stored attachments.
   */
  generateUrlResolver(analysis: ProjectAnalysis): Promise<GeneratedFile[]>

  requiredEnvVars(analysis: ProjectAnalysis): string[]

  /**
   * Returns the name of the storage bucket configured for this project.
   */
  getBucketName(analysis: ProjectAnalysis): string
}

// ---------------------------------------------------------------------------
// UI adapter plugin
// ---------------------------------------------------------------------------

export interface UIAdapterPlugin {
  readonly meta: PluginMeta & { kind: "ui" }

  detect(files: ProjectFiles): Promise<DetectionResult<DetectedUI>>

  /**
   * Generate the feedback widget component tailored to the detected UI library.
   */
  generateWidgetComponent(analysis: ProjectAnalysis): Promise<GeneratedFile[]>

  /**
   * Generate any provider wrapper or global style additions needed.
   */
  generateProviderFiles(analysis: ProjectAnalysis): Promise<GeneratedFile[]>
}

// ---------------------------------------------------------------------------
// Top-level wizard plugin (composes all adapters)
// ---------------------------------------------------------------------------

export interface FeedbackWizardPlugin {
  readonly meta: PluginMeta & { kind: "wizard" }

  auth: AuthAdapterPlugin
  orm: ORMAdapterPlugin
  storage: StorageAdapterPlugin
  ui: UIAdapterPlugin

  /**
   * Called once after all adapters have generated their files and all shell
   * commands have run. Use for any cross-cutting finishing touches.
   */
  onPostInstall?(analysis: ProjectAnalysis): Promise<void>

  /**
   * Called if the installation fails. Use to surface plugin-specific
   * troubleshooting hints.
   */
  onRollback?(analysis: ProjectAnalysis, reason: Error): Promise<void>
}

// ---------------------------------------------------------------------------
// Plugin factory
// ---------------------------------------------------------------------------

/**
 * A PluginFactory is the default export of every plugin package.
 * It receives the resolved `ProjectAnalysis` and returns a fully configured
 * `FeedbackWizardPlugin` instance.
 *
 * This deferred construction pattern allows plugins to be lazy and only
 * instantiate heavy dependencies when they are actually needed.
 */
export type PluginFactory = (analysis: ProjectAnalysis) => FeedbackWizardPlugin

/**
 * Type guard — verifies an unknown value is a valid PluginFactory.
 * Calls the function with no arguments to check that the returned object
 * has at least a `type` string property.
 */
export function isPluginFactory(value: unknown): value is PluginFactory {
  if (typeof value !== "function") return false
  try {
    const result = (value as () => unknown)()
    return (
      typeof result === "object" &&
      result !== null &&
      "type" in result &&
      typeof (result as Record<string, unknown>).type === "string"
    )
  } catch {
    return false
  }
}

// ---------------------------------------------------------------------------
// Plugin registry entry (used internally by the CLI)
// ---------------------------------------------------------------------------

export type RegisteredPlugin = {
  packageName: string
  factory: PluginFactory
  contractVersion: PluginContractVersion
}
